// Date: 7/3/2014 7:11:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.teamsao.mcsao.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class KoboldTest extends ModelBase {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;

	public KoboldTest() {
		textureWidth = 64;
		textureHeight = 32;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-4F, -8F, -4F, 8, 8, 8);
		this.head.setRotationPoint(0F, 0F, 0F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		this.body = new ModelRenderer(this, 16, 16);
		this.body.addBox(-4F, 0F, -2F, 8, 12, 4);
		this.body.setRotationPoint(0F, 0F, 0F);
		this.body.setTextureSize(64, 32);
		this.body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		this.rightarm = new ModelRenderer(this, 40, 16);
		this.rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
		this.rightarm.setRotationPoint(-5F, 2F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0F);
		this.leftarm = new ModelRenderer(this, 40, 16);
		this.leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
		this.leftarm.setRotationPoint(5F, 2F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 0, 16);
		this.rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		this.rightleg.setRotationPoint(-2F, 12F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		this.leftleg = new ModelRenderer(this, 0, 16);
		this.leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		this.leftleg.setRotationPoint(2F, 12F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
	}
	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.head.render(f5);
		this.body.render(f5);
		this.rightarm.render(f5);
		this.leftarm.render(f5);
		this.rightleg.render(f5);
		this.leftleg.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.rightleg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.leftleg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
        this.rightarm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
        this.leftarm.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	}
	
    public int func_78104_a()
    {
        return 20;
    }

}
