// Date: 7/22/2014 9:57:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.sao.models.weapons;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLambentLight extends ModelBase
{
  //fields
    ModelRenderer main_blade;
    ModelRenderer tip_1;
    ModelRenderer tip_2;
    ModelRenderer tip_3;
    ModelRenderer handle_1;
    ModelRenderer bulb_1;
    ModelRenderer bulb_2;
    ModelRenderer bulb_3;
    ModelRenderer bulb4;
    ModelRenderer hilt_bar;
    ModelRenderer hilt_1;
    ModelRenderer hilt_2;
    ModelRenderer hilt_3;
    ModelRenderer hilt_4;
    ModelRenderer Hilt_extension1;
    ModelRenderer Hilt_extension;
    ModelRenderer Hilt_jewel1;
    ModelRenderer Hilt_jewel;
    ModelRenderer blade_2;
  
  public ModelLambentLight()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      main_blade = new ModelRenderer(this, 20, 29);
      main_blade.addBox(0F, 0F, 0F, 20, 1, 2);
      main_blade.setRotationPoint(0F, 0F, 0F);
      main_blade.setTextureSize(64, 32);
      main_blade.mirror = true;
      setRotation(main_blade, 0F, 0F, 0F);
      tip_1 = new ModelRenderer(this, 46, 0);
      tip_1.addBox(0F, 0F, 0F, 1, 1, 1);
      tip_1.setRotationPoint(19.5F, 0F, 0.75F);
      tip_1.setTextureSize(64, 32);
      tip_1.mirror = true;
      setRotation(tip_1, 0F, 0F, 0F);
      tip_2 = new ModelRenderer(this, 40, 0);
      tip_2.addBox(0F, 0F, 0F, 1, 1, 1);
      tip_2.setRotationPoint(19.5F, 0F, 0.25F);
      tip_2.setTextureSize(64, 32);
      tip_2.mirror = true;
      setRotation(tip_2, 0F, 0F, 0F);
      tip_3 = new ModelRenderer(this, 34, 0);
      tip_3.addBox(0F, 0F, 0F, 1, 1, 1);
      tip_3.setRotationPoint(20F, 0F, 0.5F);
      tip_3.setTextureSize(64, 32);
      tip_3.mirror = true;
      setRotation(tip_3, 0F, 0F, 0F);
      handle_1 = new ModelRenderer(this, 0, 30);
      handle_1.addBox(0F, 0F, 0F, 5, 1, 1);
      handle_1.setRotationPoint(-6F, 0F, 0.5F);
      handle_1.setTextureSize(64, 32);
      handle_1.mirror = true;
      setRotation(handle_1, 0F, 0F, 0F);
      bulb_1 = new ModelRenderer(this, 29, 0);
      bulb_1.addBox(0F, 0F, 0F, 1, 1, 1);
      bulb_1.setRotationPoint(-6.5F, 0.2F, 0.3F);
      bulb_1.setTextureSize(64, 32);
      bulb_1.mirror = true;
      setRotation(bulb_1, 0F, 0F, 0F);
      bulb_2 = new ModelRenderer(this, 24, 0);
      bulb_2.addBox(0F, 0F, 0F, 1, 1, 1);
      bulb_2.setRotationPoint(-6.5F, -0.2F, 0.3F);
      bulb_2.setTextureSize(64, 32);
      bulb_2.mirror = true;
      setRotation(bulb_2, 0F, 0F, 0F);
      bulb_3 = new ModelRenderer(this, 19, 0);
      bulb_3.addBox(0F, 0F, 0F, 1, 1, 1);
      bulb_3.setRotationPoint(-6.5F, 0.2F, 0.7F);
      bulb_3.setTextureSize(64, 32);
      bulb_3.mirror = true;
      setRotation(bulb_3, 0F, 0F, 0F);
      bulb4 = new ModelRenderer(this, 14, 0);
      bulb4.addBox(0F, 0F, 0F, 1, 1, 1);
      bulb4.setRotationPoint(-6.5F, -0.2F, 0.7F);
      bulb4.setTextureSize(64, 32);
      bulb4.mirror = true;
      setRotation(bulb4, 0F, 0F, 0F);
      hilt_bar = new ModelRenderer(this, 0, 25);
      hilt_bar.addBox(0F, 0F, 0F, 1, 3, 1);
      hilt_bar.setRotationPoint(-1F, -1F, 0.5F);
      hilt_bar.setTextureSize(64, 32);
      hilt_bar.mirror = true;
      setRotation(hilt_bar, 0F, 0F, 0F);
      hilt_1 = new ModelRenderer(this, 0, 20);
      hilt_1.addBox(0F, 0F, 0F, 1, 1, 3);
      hilt_1.setRotationPoint(-1F, -2F, -0.5F);
      hilt_1.setTextureSize(64, 32);
      hilt_1.mirror = true;
      setRotation(hilt_1, 0F, 0F, 0F);
      hilt_2 = new ModelRenderer(this, 0, 15);
      hilt_2.addBox(0F, 0F, 0F, 1, 1, 3);
      hilt_2.setRotationPoint(-1F, 2F, -0.5F);
      hilt_2.setTextureSize(64, 32);
      hilt_2.mirror = true;
      setRotation(hilt_2, 0F, 0F, 0F);
      hilt_3.mirror = true;
      hilt_3 = new ModelRenderer(this, 0, 10);
      hilt_3.addBox(0F, 0F, 0F, 1, 3, 1);
      hilt_3.setRotationPoint(-1F, -1F, -1.5F);
      hilt_3.setTextureSize(64, 32);
      hilt_3.mirror = true;
      setRotation(hilt_3, 0F, 0F, 0F);
      hilt_3.mirror = false;
      hilt_4 = new ModelRenderer(this, 0, 5);
      hilt_4.addBox(0F, 0F, 0F, 1, 3, 1);
      hilt_4.setRotationPoint(-1F, -1F, 2.5F);
      hilt_4.setTextureSize(64, 32);
      hilt_4.mirror = true;
      setRotation(hilt_4, 0F, 0F, 0F);
      Hilt_extension1 = new ModelRenderer(this, 9, 0);
      Hilt_extension1.addBox(0F, 0F, 0F, 1, 1, 1);
      Hilt_extension1.setRotationPoint(-2F, -2F, 0.5F);
      Hilt_extension1.setTextureSize(64, 32);
      Hilt_extension1.mirror = true;
      setRotation(Hilt_extension1, 0F, 0F, 0F);
      Hilt_extension1 = new ModelRenderer(this, 9, 3);
      Hilt_extension1.addBox(0F, 0F, 0F, 1, 1, 1);
      Hilt_extension1.setRotationPoint(-2F, 2F, 0.5F);
      Hilt_extension1.setTextureSize(64, 32);
      Hilt_extension1.mirror = true;
      setRotation(Hilt_extension1, 0F, 0F, 0F);
      Hilt_jewel1 = new ModelRenderer(this, 19, 12);
      Hilt_jewel1.addBox(0F, 0F, 0F, 1, 1, 1);
      Hilt_jewel1.setRotationPoint(-1.7F, 2.3F, 0.5F);
      Hilt_jewel1.setTextureSize(64, 32);
      Hilt_jewel1.mirror = true;
      setRotation(Hilt_jewel1, 0F, 0F, 0F);
      Hilt_jewel1 = new ModelRenderer(this, 19, 9);
      Hilt_jewel1.addBox(0F, 0F, 0F, 1, 1, 1);
      Hilt_jewel1.setRotationPoint(-1.7F, -2.3F, 0.5F);
      Hilt_jewel1.setTextureSize(64, 32);
      Hilt_jewel1.mirror = true;
      setRotation(Hilt_jewel1, 0F, 0F, 0F);
      blade_2 = new ModelRenderer(this, 58, 0);
      blade_2.addBox(0F, 0F, 0F, 2, 2, 1);
      blade_2.setRotationPoint(0F, -0.5F, 1.3F);
      blade_2.setTextureSize(64, 32);
      blade_2.mirror = true;
      setRotation(blade_2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    main_blade.render(f5);
    tip_1.render(f5);
    tip_2.render(f5);
    tip_3.render(f5);
    handle_1.render(f5);
    bulb_1.render(f5);
    bulb_2.render(f5);
    bulb_3.render(f5);
    bulb4.render(f5);
    hilt_bar.render(f5);
    hilt_1.render(f5);
    hilt_2.render(f5);
    hilt_3.render(f5);
    hilt_4.render(f5);
    Hilt_extension1.render(f5);
    Hilt_extension1.render(f5);
    Hilt_jewel1.render(f5);
    Hilt_jewel1.render(f5);
    blade_2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
